const Express = require('express')
const http = require('http')
const app = Express()
const usersRouter = require('./routes/users')
const authRouter = require('./routes/auth')
const imagesRouter = require('./routes/images')
const messagesRouter = require('./routes/messages')
const helmet = require('helmet')
const compression = require('compression')
const bodyParser = require('body-parser')
const port = process.env.PORT || 3000

app.use(bodyParser.json({limit: '50mb'}))
app.use(bodyParser.urlencoded({limit: '50mb', extended: true}))
app.use('/users', usersRouter)
app.use('/auth', authRouter)
app.use('/images', imagesRouter)
app.use('/messages', messagesRouter)
app.use(helmet())
app.use(compression())
app.server = http.createServer(app)
const setupSocket = require('./socket')
setupSocket(app)
app.server.listen(port)
console.log(`Listening to port ${port}...`)
module.exports.clients = clients
